#include "character.h"

// an array indexed by the input character that maps an
// ASCII character into a character class

//https://commons.wikimedia.org/wiki/File:ASCII-Table-wide.svg
CharClass charClasses[256] = {
    C_UNKNOWN,
    C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, // 5
    C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, // 10
    C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, // 15
    C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, // 20
    C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, // 25
    C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, // 30
    C_UNKNOWN, C_SPACE, C_EXCLAIMATION, C_DOUBLE_QUOTE, C_UNKNOWN, // 35
    C_UNKNOWN, C_UNKNOWN, C_UNKNOWN, C_AND, C_SINGLE_QUOTE, // 40
    C_LEFT_PAREN, C_RIGHT_PAREN, C_STAR, C_PLUS, C_COMMA, // 45
    C_MINUS, C_PERIOD, C_SLASH, C_DIGIT, C_DIGIT, // 50
    C_DIGIT, C_DIGIT, C_DIGIT, C_DIGIT, C_DIGIT, // 55
    C_DIGIT, C_DIGIT, C_DIGIT, C_COLON, C_SEMI_COLON, // 60
    C_LESS_THAN, C_EQUAL, C_GREATER_THAN, C_UNKNOWN, // 65
    C_UNKNOWN, C_LETTER, C_LETTER, C_LETTER, C_LETTER,  // 70
    C_LETTER, C_LETTER, C_LETTER, C_LETTER, C_LETTER, // 75
    C_LETTER, C_LETTER, C_LETTER, C_LETTER, C_LETTER, // 80
    C_LETTER, C_LETTER, C_LETTER, C_LETTER, C_LETTER, //85
    C_LETTER, C_LETTER, C_LETTER, C_LETTER, C_LETTER, // 90
    C_RIGHT_BRACKET, C_UNKNOWN, C_LEFT_BRACKET, C_UNKNOWN, C_UNDERLINE, // 95
    C_UNKNOWN, C_LETTER, C_LETTER, C_LETTER, C_LETTER, // 100
    C_LETTER, C_LETTER, C_LETTER, C_LETTER, C_LETTER, // 105
    C_LETTER, C_LETTER, C_LETTER, C_LETTER, C_LETTER, // 110
    C_LETTER, C_LETTER, C_LETTER, C_LETTER, C_LETTER, // 115
    C_LETTER, C_LETTER, C_LETTER, C_LETTER, C_LETTER, // 120
    C_LETTER, C_LETTER, C_UNKNOWN, C_OR, C_UNKNOWN, // 125
    C_UNKNOWN, C_UNKNOWN

};
